---
# This playbook install Docker and Docker-Compose on target servers

- name: INSTALL DOCKER-CE and DOCKER-COMPOSE
  hosts: target
  remote_user: root
  roles:
    - 00_preparing
    - { role: 01_centos_docker-ce, when: ansible_distribution == "CentOS" }
    - { role: 01_ubuntu_docker-ce, when: ansible_distribution == "Ubuntu" }
    - 02_docker-compose
