---
# Install Docker-CE

- name: Uninstall old versions if exists
  apt: name={{ item }} state=absent
  loop:
    - docker-ce
    - docker
    - docker-engine
    - docker.io

- name: Run "apt-get update"
  apt: update_cache=yes

- name: Install packages to allow apt to use a repository over HTTPS
  apt: name={{ item }} state=present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present

- name: Add docker stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable state=present

- name: Run "apt-get update"
  apt: update_cache=yes
  
- name: Install Docker CE
  apt: name={{ item }} state=present
  loop:
    - docker-ce

- name: Enable and Start Docker service
  service: name=docker state=started enabled=yes
